### ISSUE TITLE
Not enough Hello World

### ISSUE THREAD

**Issue by EncryptedData** [cameronwhite4121/first-repository#1]
Hello,

I am looking at this project and I am not seeing enough Hello World in this project...

**Comment by cameronwhite4121** [comment]
![Capture](https://github.com/cameronwhite4121/first-repository/assets/143460157/f5425a16-e60e-4560-84ca-bbd84c58813b)

**Comment by cameronwhite4121** [comment]
Edited code to add more Hello World

**Comment by EncryptedData** [comment]
You know you can just do:
```
while(true) {
    alert("Hello World");
}
```

instead?

**Comment by cameronwhite4121** [comment]
Wonderful advice, I'll be sure to implement this in future team projects!
